package com.example.myservice.model.impl;

import com.example.myservice.model.Locality;
import com.example.myservice.service.LocalityLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Locality service. Represents a row in the &quot;hh_api_Locality&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LocalityImpl}.
 * </p>
 *
 * @author hamid
 * @see LocalityImpl
 * @see com.example.myservice.model.Locality
 * @generated
 */
public abstract class LocalityBaseImpl extends LocalityModelImpl
    implements Locality {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a locality model instance should use the {@link Locality} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LocalityLocalServiceUtil.addLocality(this);
        } else {
            LocalityLocalServiceUtil.updateLocality(this);
        }
    }
}
