package com.example.myservice.model.impl;

import com.example.myservice.model.Region;
import com.example.myservice.service.RegionLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Region service. Represents a row in the &quot;hh_api_Region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegionImpl}.
 * </p>
 *
 * @author hamid
 * @see RegionImpl
 * @see com.example.myservice.model.Region
 * @generated
 */
public abstract class RegionBaseImpl extends RegionModelImpl implements Region {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a region model instance should use the {@link Region} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RegionLocalServiceUtil.addRegion(this);
        } else {
            RegionLocalServiceUtil.updateRegion(this);
        }
    }
}
