package com.example.myservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Locality service. Represents a row in the &quot;hh_api_Locality&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.myservice.model.impl.LocalityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.myservice.model.impl.LocalityImpl}.
 * </p>
 *
 * @author hamid
 * @see Locality
 * @see com.example.myservice.model.impl.LocalityImpl
 * @see com.example.myservice.model.impl.LocalityModelImpl
 * @generated
 */
public interface LocalityModel extends BaseModel<Locality> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a locality model instance should use the {@link Locality} interface instead.
     */

    /**
     * Returns the primary key of this locality.
     *
     * @return the primary key of this locality
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this locality.
     *
     * @param primaryKey the primary key of this locality
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this locality.
     *
     * @return the ID of this locality
     */
    public long getId();

    /**
     * Sets the ID of this locality.
     *
     * @param id the ID of this locality
     */
    public void setId(long id);

    /**
     * Returns the name of this locality.
     *
     * @return the name of this locality
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this locality.
     *
     * @param name the name of this locality
     */
    public void setName(String name);

    /**
     * Returns the parent ID of this locality.
     *
     * @return the parent ID of this locality
     */
    public long getParentId();

    /**
     * Sets the parent ID of this locality.
     *
     * @param parentId the parent ID of this locality
     */
    public void setParentId(long parentId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Locality locality);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Locality> toCacheModel();

    @Override
    public Locality toEscapedModel();

    @Override
    public Locality toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
