package com.example.myservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Vacancy service. Represents a row in the &quot;hh_api_Vacancy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.myservice.model.impl.VacancyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.myservice.model.impl.VacancyImpl}.
 * </p>
 *
 * @author hamid
 * @see Vacancy
 * @see com.example.myservice.model.impl.VacancyImpl
 * @see com.example.myservice.model.impl.VacancyModelImpl
 * @generated
 */
public interface VacancyModel extends BaseModel<Vacancy> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a vacancy model instance should use the {@link Vacancy} interface instead.
     */

    /**
     * Returns the primary key of this vacancy.
     *
     * @return the primary key of this vacancy
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this vacancy.
     *
     * @param primaryKey the primary key of this vacancy
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this vacancy.
     *
     * @return the ID of this vacancy
     */
    public long getId();

    /**
     * Sets the ID of this vacancy.
     *
     * @param id the ID of this vacancy
     */
    public void setId(long id);

    /**
     * Returns the name of this vacancy.
     *
     * @return the name of this vacancy
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this vacancy.
     *
     * @param name the name of this vacancy
     */
    public void setName(String name);

    /**
     * Returns the published at of this vacancy.
     *
     * @return the published at of this vacancy
     */
    @AutoEscape
    public String getPublishedAt();

    /**
     * Sets the published at of this vacancy.
     *
     * @param publishedAt the published at of this vacancy
     */
    public void setPublishedAt(String publishedAt);

    /**
     * Returns the employer of this vacancy.
     *
     * @return the employer of this vacancy
     */
    @AutoEscape
    public String getEmployer();

    /**
     * Sets the employer of this vacancy.
     *
     * @param employer the employer of this vacancy
     */
    public void setEmployer(String employer);

    /**
     * Returns the salary of this vacancy.
     *
     * @return the salary of this vacancy
     */
    @AutoEscape
    public String getSalary();

    /**
     * Sets the salary of this vacancy.
     *
     * @param salary the salary of this vacancy
     */
    public void setSalary(String salary);

    /**
     * Returns the address of this vacancy.
     *
     * @return the address of this vacancy
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this vacancy.
     *
     * @param address the address of this vacancy
     */
    public void setAddress(String address);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Vacancy vacancy);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Vacancy> toCacheModel();

    @Override
    public Vacancy toEscapedModel();

    @Override
    public Vacancy toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
